### PR TITLE
Add methods for sf objects

### PR DESCRIPTION
**Pull request by agila5**

### CODE REVIEW

**Comment by thengl** [comment]
Looks good. Can you also add more examples in the README.md?

**Comment by agila5** [comment]
> Looks good. Can you also add more examples in the README.md?

Thanks! Yes, I'm working on the examples right now and this evening I will update the docs and tests (with testthat). The main problem is that I don't know how to work with `stars` objects since I did some tests locally but I don't have enough experience, sorry. I hope I will be able to complete it after the lecture of Prof. Pebesma.

**Comment by thengl** [comment]
Yes please check next with Edzer how to visualize stars objects in KML.

**Comment by agila5** [comment]
Hi! I think the sf component of the project is ready for review.

**Pull request merged**
